### ISSUE TITLE
Embedding DC Layout in weighted nets always considers edge weights

### ISSUE THREAD

**Issue by oxy86** [socnetv/app#103]
There is a bug when embedding DC layout on weighted networks without first running the respective index computation -- if you don't do this, the app will always compute the layout on the weighted network even if you had answered "No" in app prompt ("Consider edge weights?").

**Comment by LMCJILTON** [comment]
I'm not sure I understand. What do I need to do prior to successfully
getting the clique to display?



Leah Mcjilton

West Virginia University

Instructional Design & Technology


m: +304 669 1438

329 Evergreen Drive Bridgeport, WV 26330

**Comment by oxy86** [comment]
Hello Leah, this bug has been reported by another person (I uploaded here to let others know about it). 

Have you also experienced this issue?

**Comment by oxy86** [comment]
This has been fixed in v2.9. I am closing it.
