### ISSUE TITLE
Bug in PageRank results

### ISSUE THREAD

**Issue by Michele971** [socnetv/app#135]
We are using the web crawler features and, after opened the HTML file resulting from Page Rank calculation (on our network), the label with the links of the page are "cutted" so we can not see the whole URL. We have opened the HTML file and we saw that the links (in <td> tag) are truncated. 

Here a screen of the issue:
<img width="889" alt="bug" src="https://user-images.githubusercontent.com/68105769/149766333-9719ab9d-1824-4481-8dcd-9c2a93b32281.png">

The length of the chars in the field is 99 at max.

**Comment by oxy86** [comment]
Hello and thanks for using SocNetV. You can manage the width of the label from the app Settings. Go to General tab and on the Reports section you will see a "Labels length" spinbox where you can set any size you want (up to a maximum of 99 chars). After that, run the calculation again (to create the HTML file again) and the labels will be as large as you defined them.
Let me know if that works for you.
