### ISSUE TITLE
Can't open/import Pajek file

### ISSUE THREAD

**Issue by paroberge** [socnetv/app#27]
Everytime I try to open a Pajek formatted file, including my own or the one provided in SocNetv manual, I'm getting an error message "XML tokenstring at line 1 is invalid".

**Comment by oxy86** [comment]
Hello, that message indicates that SocNetV thinks you are trying to open a XML (GraphML) file.

Pajek files should be imported via the menu Network -> Import (and have a .pajek or .net or .paj extension). Did you try that?

If you did and still have errors, please upload a part (the beginning of) the file here to inspect it.

**Comment by paroberge** [comment]
Yes, i try to open using import method. I just downloaded version 2.1 and
its is working fine on that version.

**Comment by oxy86** [comment]
ΟΚ, closing this.

**Comment by paroberge** [comment]
I'd prefer using the latest revision. Is this fixed in the dev build?

Pierre
pierre@paroberge.com<mailto:pierre@paroberge.com>
________________________________

**Comment by oxy86** [comment]
Hello, can you please upload your data file to debug this problem in 2.2 ?

**Comment by paroberge** [comment]
Ok, now i can load the pajek file in V2.2
Seems that installing v2.1 solved the problem that exit with a fresh install of v2.2

This is the test file (text.net) I used
*Network
*Vertices 17 2	
1 "21" ellipse
2 "24" diamond
3 "27" diamond
4 "30" ellipse
5 "33" diamond
6 "36" diamond
7 "39" ellipse
8 "42" ellipse
9 "45" ellipse
10 "48" diamond
11 "51" diamond
12 "54" ellipse
13 "57" ellipse
14 "60" ellipse
15 "63" diamond
16 "66" ellipse
17 "69" ellipse
*Arcs
1 2
1 3
2 4
4 5
4 6
2 7
8 2
2 9
9 10
9 11
2 12
2 13
2 14
14 15
2 16
2 17

**Comment by oxy86** [comment]
I am not sure what has happened here and what the problem/explanation is.
SocNetV 2.2  opens easily the data file you uploaded.  I see no problem with your data. 
As a matter of fact, the data file is so simple that any version of SocNetV should open it. 
Anyway, since you don't have any problems now, I am closing this.  Have fun!
