### ISSUE TITLE
Using 1 as weight even after saying yes to weight dialogs in some cases

### ISSUE THREAD

**Issue by correia55** [socnetv/app#54]
When I import an adjacency matrix containing a weighted digraph, and then calculate the Average Distance, two dialogs appear asking me if I want to use the weights and if I want to inverted them and, even though I say yes to both of them, the distance gets calculated using 1 as the weight of every existing edge. I confirmed this by then checking the Geodesic Distance Matrix.
This does not happen If instead I calculate the Geodesic Distance Matrix (or the Eccenctricity (does are the only ones I tested, not sure about any others)) first and say yes to both dialogs. In this case, everything is well calculated and if I check the Average Distance, it presents the correct result using the inverted weights.

**Comment by oxy86** [comment]
Hi. Seems like hit a bug :)
What version are you using please?

**Comment by correia55** [comment]
Sorry about the delay in my response, the version I have installed is 2.3 (Build: Tue Jan 31 15:16:27 EET 2017).

**Comment by oxy86** [comment]
Hello friend, this bug is fixed in version 2.4 which has been released today. Please download the new version and test for yourself...
