### ISSUE TITLE
Web Crawler crash the program

### ISSUE THREAD

**Issue by jlarrosa042** [socnetv/app#55]
Hi. Great product! I had a problem with Web Crawler... it just crashed the program each and every time I collect data from a website and it gave me no time to save it. Thanks!
Juan

**Comment by oxy86** [comment]
Hi, please tell us what SocNetV version you have installed and what is your OS. 
Does this crash occur with every website you try or a particular one?

**Comment by oxy86** [comment]
Can you please try the version in the develop branch?

**Comment by oxy86** [comment]
Version 2.4 released a month ago contains an improved web crawler. Please download the new version and test again. I will close this issue now.
